export const COMPLAINT_AUTH_SUCCESS = "COMPLAINT_AUTH_SUCCESS";
export const COMPLAINT_AUTH_FAIL = "COMPLAINT_AUTH_FAIL";

export const COMPLAINT_NO_USER = "COMPLAINT_NO_USER";

export const COMPLAINT_REGISTER_SUCCESS = "COMPLAINT_REGISTER_SUCCESS";
export const COMPLAINT_REGISTER_FAIL = "COMPLAINT_REGISTER_FAIL";

export const COMPLAINT_LOADING = "COMPLAINT_LOADING";
export const COMPLAINT_LOADED = "COMPLAINT_LOADED";

export const COMPLAINT_GET_LIST_USER = "COMPLAINT_GET_LIST_USER";
export const COMPLAINT_GET_LIST_ALL = "COMPLAINT_GET_LIST_ALL";

export const COMPLAINT_GET_UPLOAD_FILE = "COMPLAINT_GET_UPLOAD_FILE";

export const COMPLAINT_ADD_LIST = "COMPLAINT_ADD_LIST";
export const COMPLAINT_LAST_LIST = "COMPLAINT_LAST_LIST";
export const COMPLAINT_SELECT_LIST = "COMPLAINT_SELECT_LIST";
export const COMPLAINT_UPDATE_LIST = "COMPLAINT_UPDATE_LIST";

export const COMPLAINT_ERROR = "COMPLAINT_ERROR";

export const COMPLAINT_CLEAN_TRIGGER = "COMPLAINT_CLEAN_TRIGGER";
