// AUTH AND REGISTER
export const RESEARCH_AUTH_SUCCESS = "RESEARCH_AUTH_SUCCESS";
export const RESEARCH_AUTH_FAIL = "RESEARCH_AUTH_FAIL";
export const RESEARCH_REGISTER_SUCCESS = "RESEARCH_REGISTER_SUCCESS";
export const RESEARCH_REGISTER_FAIL = "RESEARCH_REGISTER_FAIL";

// LOAD DATA
export const RESEARCH_LOADING = "RESEARCH_LOADING";
export const RESEARCH_LOADED = "RESEARCH_LOADED";

// UPLOAD FILE
export const RESEARCH_GET_UPLOAD_FILE = "RESEARCH_GET_UPLOAD_FILE";
export const RESEARCH_GET_PROJECT_UPLOAD_FILE =
  "RESEARCH_GET_PROJECT_UPLOAD_FILE";

// LOADING OVERLAY
export const LOADING_OVERLAY = "LOADING_OVERLAY";
export const CLOSE_OVERLAY = "CLOSE_OVERLAY";

//LOGS
export const FORM_LOG = "FORM_LOG";
export const PROJECT_FORM_LOG = "PROJECT_FORM_LOG";

//  TAGS
export const COLLECT_TAG = "COLLECT_TAG";
export const CLEAR_TAG = "CLEAR_TAG";

// Student
export const STUDENT_TAG = "STUDENT_TAG";
export const CLEAR_STUDENT_TAG = "CLEAR_STUDENT_TAG";

// RESEARCH LIST
export const RESEARCH_ADD_LIST_SUCCESS = "RESEARCH_ADD_LIST_SUCCESS";
export const RESEARCH_SEND_MAIL_COMMITTEE = "RESEARCH_SEND_MAIL_COMMITTEE";
export const RESEARCH_SEND_NO_COMMITTEE = "RESEARCH_NO_MAIL_COMMITTEE";

export const RESEARCH_GET_LIST_USER = "RESEARCH_GET_LIST_USER";
export const RESEARCH_GET_LIST_ADMIN = "RESEARCH_GET_LIST_ADMIN";
export const RESEARCH_GET_LIST_COMMITTEE = "RESEARCH_GET_LIST_COMMITTEE";

// RESEARCH GET E-MAIL
export const RESEARCH_GET_EMAIL_USER = "RESEARCH_GET_EMAIL_USER";
export const RESEARCH_GET_EMAIL_COMMITTEE = "RESEARCH_GET_EMAIL_COMMITTEE";
export const RESEARCH_GET_EMAIL_ADMIN = "RESEARCH_GET_EMAIL_ADMIN";

// RESEARCH EDIT
export const RESEARCH_EDIT_UPDATE = "RESEARCH_EDIT_UPDATE";

// RESEARCH DETAIL
export const RESEARCH_GET_DETAIL = "RESEARCH_GET_DETAIL";

// RESEARCH STATUS
export const RESEARCH_UPDATE_STATUS = "RESEARCH_UPDATE_STATUS";

// RESEARCH PROJECT
export const RESEARCH_PROJECT_GET_USER = "RESEARCH_PROJECT_GET_USER";
export const RESEARCH_PROJECT_GET_ADMIN = "RESEARCH_PROJECT_GET_ADMIN";
export const RESEARCH_PROJECT_GET_COMMITTE = "RESEARCH_PROJECT_GET_COMMITTE";
export const RESEARCH_PROJECT_GET_DETAIL = "RESEARCH_PROJECT_GET_DETAIL";

// RESEARCH PROJECT EMAIL
export const RESEARCH_PROJECT_SEND_MAIL_ADMIN =
  "RESEARCH_PROJECT_SEND_MAIL_ADMIN";
export const RESEARCH_PROJECT_SEND_NO_ADMIN = "RESEARCH_PROJECT_SEND_NO_ADMIN";
// RESEARCH PROJECT GET EMAIL
export const RESEARCH_PROJECT_GET_EMAIL_ADMIN =
  "RESEARCH_PROJECT_GET_EMAIL_ADMIN";

// RESEARCH PROJECT EDIT
export const RESEARCH_PROJECT_EDIT_UPDATE = "RESEARCH_PROJECT_EDIT_UPDATE";

// GET ERROR
export const RESEARCH_ERROR = "RESEARCH_ERROR";

// DEADLINE
export const RESEARCH_ADD_DEADLINE_ADMIN = "RESEARCH_ADD_DEADLINE_ADMIN";
export const RESEARCH_GET_DEADLINE_ADMIN = "RESEARCH_GET_DEADLINE_ADMIN";
export const RESEARCH_ADD_DEADLINECHECK_ADMIN =
  "RESEARCH_ADD_DEADLINECHECK_ADMIN";
export const RESEARCH_GET_DEADLINECHECK_ADMIN =
  "RESEARCH_GET_DEADLINECHECK_ADMIN";

// REPORT
export const RESEARCH_GET_REPORT_ADMIN = "RESEARCH_GET_REPORT_ADMIN";
export const RESEARCH_GET_REPORT_COMMITTEE = "RESEARCH_GET_REPORT_COMMITTEE";
export const RESEARCH_GET_REPORT_USER = "RESEARCH_GET_REPORT_USER";
