export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const START_APP = "START_APP";
export const AUTH_ERROR = "AUTH_ERROR";

export const PAGE_LOADING = "PAGE_LOADING";
export const PAGE_LOADED = "PAGE_LOADED";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_SET = "USER_SET";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const SET_DEPARTMENT = "SET_DEPARTMENT";
export const CLOSE_DEPARTMENT = "CLOSE_DEPARTMENT";

export const SET_USERLIST = "SET_USERLIST";
export const CLOSE_USERLIST = "CLOSE_USERLIST";

export const GET_ALL_SERVICE_USER = "GET_ALL_SERVICE_USER";
export const GET_USER_SERVICE = "GET_USER_SERVICE";
export const GET_CURRENT_USER_SERVICE = "GET_CURRENT_USER_SERVICE";
export const ERROR_GET_SERVICE = "ERROR_GET_SERVICE";
export const SEND_ACTIVE_SERVICE = "SEND_ACTIVE_SERVICE";
